name: borb-RVA23S64
compiler_exe: riscv64-unknown-elf-gcc
objdump_exe: riscv64-unknown-elf-objdump
ref_model_exe: sail_riscv_sim
udb_config: ../riscv-arch-test/config/sail/sail-RVA23S64/sail-RVA23S64.yaml
linker_script: link.ld
dut_include_dir: .
